CREATE TABLE [core].[User]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Email] NVARCHAR(200) NOT NULL,
	[FirstName] NVARCHAR(50) NOT NULL,
	[LastName] NVARCHAR(150) NOT NULL,
	[BirthDate] DATETIME2(7) NOT NULL
)
